package com.example.digitai;

import android.util.Base64;

public final class DigitModel {
    private static final int PROTO_COUNT = 30;
    private static final int FEATURES = 64;
    private static final String MODEL_B64 = "AAAx160cAAAACbfs368FAAAw7I484SwAAE7oPAS1WgAAU98hAbBrAAAr5zwn21UAAArAx83jGAAAADLO2E8BAAABXMXHZAIAAAzOynvWMQAALuFEBoNbAABM0BYAbG0AAGClAgCQWgAARcEEHcwuAAAX43O2qwYAAABg5rEhAAAAAEHTsyUAAAAS2ce2rAYAAE/iJxrDLwAAYa4KAn5yAABnmwQAYYkAADnMCQCAhAAACNOTc+dFAAAAP9rmfwgAAAAsw8NHCAAAAU7r+n4LAAAKZfP8aQUAABN+9fJIAQAADYf15S4AAAAKkPfdJQAAAAN2890xAgAAACy40koGAAAAABWwxicAAAANbfTpMQAAGXrd+dgdAABAxcbh0RIAACJjXtnFFAAABxQ42MUSAAAAAC7V2yAAAAAAFrXPIQAAAHTGHQAAAAACcPRGAQAAAA54+3ACAAAADn/7ow0AAAACP77SJgAAAAAJVdlcBAAAAFar6NKQRAAAYOr5/O+XABa18JwaAAABbevByD8AAABUbWDSMgAAAA4WkMQPAAAAACbjawAAAAAKkdkYDxEBACPhypenYQMAFcb27MNjBQABUcHddQkAABukvbDVIQAAG2tCU+EjAAAFEw+IwREAAAMOQcNxAwAAFkWVsTMLAAEScufYlE8PAAJTxM7BizoADqnpcgcAAABa7sXPLAAAAE+XMdhEAAAAECAj30AAAAAAAVXbIQAAAAAdtrImDQAADK772rWbEgAOpdKwsaAoAAdn0OyOCAAAQdGYnOAcAAA3Wh+ysAoAAAkPZfFtAgAAAwUsscouAAAHFwMbxIAAAAp6bV7NhQEABHPf7bMqAQAPmOjxtCgAACurkajvWgAABxcqsdUkAAAADXbhWwEAAAAceNZWAAAAAA42wKsJAAAGSGHWuQ8AABCx7sFIAQAAC5Xr0DMAAABR1YPacwAAABsyUdY8AAAABDHWzDUAAAAAG4XG1isAAAsXCCXPewAAF4NXb+VoAQAHovboiwwAAAAAP946AwAAABHRqwoHAAADhdkjKkACADniYRCffQAAlOdBfetgAAOk79Pr3SQAAzBxg+59AAAAAAJG6joAAAAAEriIBQUDAAJx6TkpGQQAGed8Mn5FBgBo70eSwmMAAIXcsu/URQAAR5LB6mkHAAAKIqq/DQAAAAETzYoCAAAAAAA32DgBAAAACbfbMhEHAABt6JpZKQgAMt6Tpoo+AACF9sfu5G0AAFmsu+jGMgAABAo35VIAAAAAAD/aLwAAAAmGzte1TQEAOeLboHssAABF7m8WBwIAAFbtyJscAQAALZSb5n0IAAAJHByyqQwAAAlGg+F0BAAAB5fwoRgAAAAImb7RtzQBACXmlmdOFQAAR9lVOxcCAABU6MXNjA8AABxoP03MQgAAAwwAGbZXAAALaUqFvTMAAAmg7MVVCAAAIL7k6tNLAQBo+uGddDACAIDpWgkAAAAATtOvMwEAAAAVeMyBAgAAAAMdqrgRAAAAFWbTrg8AAAAgz+dMAQAAAAAfx14HAAAAAZvUJAIAAAAS4lEBAAAAADPePygTAQAAR+65y7ssAAAn9IdCl54BAAS+sDSjsAQAACW89cw6AQAABZy7FAAAAAA785EPAgAABJXhKQMAAAAQxd+gYwgAACLZ5rrZZAAADNWzHX64DAAAfOFpxbIPAAAJm+7VQwAAAAmm0CsAAAABZ/eWFgAAAA7BzBIAAAAAJOKjGQYAAAA58tm2XwcAACDszabXWgEAAp/kidKYBgAAEJ/t11UDAAqa69tgGQIAJ7un1ZYPAQAKJTjYlhwBABB+2PbNfgAAJqzrzF0iAAAQUOtPDAIAAASJyw0AAAAABsZ1AQAAAAAAIqva5rQtAAOP2p/Qxx8ABnY9D758BgALVT594VEAAAxeqOfQRwAACjuJ4GAJAAAAB6GqBgAAAAAl1k8BAAAAAEzc9bUpAgAPsK+u3icAABNFCoDFDAAABidJ17Q9AAAYoOn6wFMAABdlyr1DEAAAASDkUwIAAAAAXNAWAAAAAARqxsJjBQABJNi5lcUjAAAmw36lxBgAAA+K289RBgAAC5DsqBEAAAAVx5m+MAAAABbLc89MAAAAA23fuCEAAAACSbfJYQcAAB2urYqyJAAAJaeEe7wiAAAIat7jeQkAAAVv5OFOAQAAGtJfbrkYAAAUyG1Bzz4AAAJKu96vMAAAACKm1XwOAAAYz7+qzjsAAFHjPDy2OwAAL860wZ8LAAACOLv0lwYAAAAusXnbOwAAAEfAaNNGAAAAE7vskQ0AAAARXbvidw0AFoTHgaKYDAA+3n1h2m8FADjw6ubJPgAABVxxkZ0QAAABAR6oZgAAAAUNVZ88AAAAABVwdyoAAAADetOmLAEAADbig6OrBwAAVbQsZ9keAAAxyKTR5TMAAANQkH7CTwAAAAQGD510AAADXENEq3YCAAF50t2jOAIAA2HVvVcEAAAh2Z6vxBMAACTSdrDpJgAAB3PPy+RDAAAAAhYfvmEAAAYNAgmtcwAAFIdaWNJgAQADZtbsrSEA";
    private static final String LABELS = "000111222333444555666777888999";
    private static final byte[] PROTOS = Base64.decode(MODEL_B64, Base64.DEFAULT);

    private DigitModel() {}

    public static int predict(float[] input) {
        double best = Double.MAX_VALUE;
        int bestIndex = 0;

        for (int p = 0; p < PROTO_COUNT; p++) {
            double d = 0.0;
            int base = p * FEATURES;
            for (int i = 0; i < FEATURES; i++) {
                double diff = input[i] * 255.0 - (PROTOS[base + i] & 0xff);
                d += diff * diff;
            }
            if (d < best) {
                best = d;
                bestIndex = p;
            }
        }
        return LABELS.charAt(bestIndex) - '0';
    }
}
