package com.example.sudoku;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.content.*;import android.view.*;import android.widget.*;import android.print.*;import android.print.pdf.PrintedPdfDocument;import java.util.*;
public class MainActivity extends Activity{
 Board b; int[][] sol=new int[9][9],u=new int[9][9]; boolean[][] fixed=new boolean[9][9]; int sr=-1,sc=-1,errors=0,hints=0; String level="בינוני"; TextView info; Random rnd=new Random();
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 TextView t(String s,int z,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.CENTER);if(bold)v.setTypeface(Typeface.DEFAULT,1);return v;}
 Button btn(String s){Button x=new Button(this);x.setText(s);x.setTextColor(Color.WHITE);x.setTextSize(13);x.setAllCaps(false);x.setTypeface(Typeface.DEFAULT,1);x.setBackground(bg(Color.rgb(54,61,91),15));return x;}
 public void onCreate(Bundle x){super.onCreate(x);getWindow().setStatusBarColor(Color.rgb(12,15,28));getWindow().setNavigationBarColor(Color.rgb(12,15,28));ui();}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(12),dp(6),dp(12),dp(12));r.setBackgroundColor(Color.rgb(12,15,28));
 LinearLayout h=new LinearLayout(this);TextView logo=t("🧩 סודוקו קסום",24,Color.WHITE,true);h.addView(logo,new LinearLayout.LayoutParams(0,dp(52),1));Button ng=btn("משחק חדש");h.addView(ng,new LinearLayout.LayoutParams(dp(105),dp(46)));ng.setOnClickListener(v->newGame());r.addView(h);
 LinearLayout lv=new LinearLayout(this);for(String d:new String[]{"קל","בינוני","קשה","מומחה"}){Button q=btn(d);lv.addView(q,new LinearLayout.LayoutParams(0,dp(42),1));q.setOnClickListener(v->{level=q.getText().toString();newGame();});}r.addView(lv,new LinearLayout.LayoutParams(-1,dp(48)));
 b=new Board(this);r.addView(b,new LinearLayout.LayoutParams(-1,0,1));
 LinearLayout bar=new LinearLayout(this);info=t("",12,Color.rgb(190,198,225),true);bar.addView(info,new LinearLayout.LayoutParams(0,dp(44),1));Button hi=btn("💡 רמז");bar.addView(hi,new LinearLayout.LayoutParams(dp(85),dp(44)));hi.setOnClickListener(v->hint());Button pr=btn("🖨 30 חידות");bar.addView(pr,new LinearLayout.LayoutParams(dp(105),dp(44)));pr.setOnClickListener(v->printBook());r.addView(bar);
 GridLayout nums=new GridLayout(this);nums.setColumnCount(5);for(int n=1;n<=9;n++){Button q=btn(""+n);GridLayout.LayoutParams p=new GridLayout.LayoutParams();p.width=0;p.height=dp(44);p.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);p.setMargins(dp(2),dp(2),dp(2),dp(2));nums.addView(q,p);final int z=n;q.setOnClickListener(v->put(z));}Button er=btn("⌫");GridLayout.LayoutParams ep=new GridLayout.LayoutParams();ep.width=0;ep.height=dp(44);ep.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);ep.setMargins(dp(2),dp(2),dp(2),dp(2));nums.addView(er,ep);er.setOnClickListener(v->put(0));r.addView(nums,new LinearLayout.LayoutParams(-1,dp(96)));setContentView(r);newGame();}
 void newGame(){sol=new int[9][9];fill(sol);u=copy(sol);int holes=level.equals("קל")?34:level.equals("בינוני")?43:level.equals("קשה")?51:57;for(int k=0;k<holes;k++)u[rnd.nextInt(9)][rnd.nextInt(9)]=0;fixed=new boolean[9][9];for(int i=0;i<9;i++)for(int j=0;j<9;j++)fixed[i][j]=u[i][j]!=0;errors=hints=0;sr=sc=-1;msg();b.invalidate();}
 void msg(){info.setText("רמה: "+level+"   •   טעויות: "+errors+"   •   רמזים: "+hints);}
 boolean fill(int[][]g){for(int r=0;r<9;r++)for(int c=0;c<9;c++)if(g[r][c]==0){ArrayList<Integer>a=new ArrayList<>();for(int n=1;n<=9;n++)a.add(n);Collections.shuffle(a,rnd);for(int n:a)if(ok(g,r,c,n)){g[r][c]=n;if(fill(g))return true;g[r][c]=0;}return false;}return true;}
 boolean ok(int[][]g,int r,int c,int n){for(int i=0;i<9;i++)if(g[r][i]==n||g[i][c]==n)return false;for(int i=r/3*3;i<r/3*3+3;i++)for(int j=c/3*3;j<c/3*3+3;j++)if(g[i][j]==n)return false;return true;}
 int[][]copy(int[][]a){int[][]x=new int[9][9];for(int i=0;i<9;i++)System.arraycopy(a[i],0,x[i],0,9);return x;}
 void put(int n){if(sr<0||fixed[sr][sc])return;if(n==0){u[sr][sc]=0;}else if(n==sol[sr][sc]){u[sr][sc]=n;check();}else{errors++;}msg();b.invalidate();}
 void hint(){if(sr<0||fixed[sr][sc])return;u[sr][sc]=sol[sr][sc];hints++;msg();b.invalidate();check();}
 void check(){for(int i=0;i<9;i++)for(int j=0;j<9;j++)if(u[i][j]!=sol[i][j])return;new AlertDialog.Builder(this).setTitle("🎉 כל הכבוד!").setMessage("פתרת את הסודוקו!").setPositiveButton("משחק חדש",(d,w)->newGame()).setNegativeButton("סגור",null).show();}
 class Board extends View{Paint p=new Paint(3);Board(Context c){super(c);setBackgroundColor(Color.rgb(18,22,39));}protected void onDraw(Canvas c){float z=Math.min(getWidth(),getHeight())/9f,x=(getWidth()-9*z)/2f,y=(getHeight()-9*z)/2f;p.setStyle(Paint.Style.FILL);for(int r=0;r<9;r++)for(int q=0;q<9;q++){int col=(r==sr||q==sc||(sr>=0&&r/3==sr/3&&q/3==sc/3))?Color.rgb(38,46,76):Color.rgb(24,29,50);if(r==sr&&q==sc)col=Color.rgb(83,68,142);p.setColor(col);c.drawRect(x+q*z,y+r*z,x+(q+1)*z,y+(r+1)*z,p);if(u[r][q]>0){p.setTextAlign(Paint.Align.CENTER);p.setTextSize(z*.5f);p.setColor(fixed[r][q]?Color.WHITE:(u[r][q]==sol[r][q]?Color.rgb(145,226,255):Color.rgb(255,70,90)));c.drawText(""+u[r][q],x+(q+.5f)*z,y+(r+.68f)*z,p);}}p.setStyle(Paint.Style.STROKE);for(int i=0;i<=9;i++){p.setStrokeWidth(dp(i%3==0?3:1));p.setColor(i%3==0?Color.rgb(220,225,245):Color.rgb(86,94,125));c.drawLine(x,y+i*z,x+9*z,y+i*z,p);c.drawLine(x+i*z,y,x+i*z,y+9*z,p);}}public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=1)return true;float z=Math.min(getWidth(),getHeight())/9f,x=(getWidth()-9*z)/2f,y=(getHeight()-9*z)/2f;int c=(int)((e.getX()-x)/z),r=(int)((e.getY()-y)/z);if(r>=0&&r<9&&c>=0&&c<9){sr=r;sc=c;invalidate();}return true;}}
 void printBook(){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("חוברת סודוקו 30",new PrintDocumentAdapter(){PrintedPdfDocument d;public void onLayout(PrintAttributes a,PrintAttributes o,LayoutResultCallback cb,Bundle e){d=new PrintedPdfDocument(MainActivity.this,a);cb.onLayoutFinished(new PrintDocumentInfo.Builder("sudoku-30.pdf").setContentType(PrintDocumentInfo.CONTENT_TYPE_DOCUMENT).setPageCount(30).build(),true);}public void onWrite(PageRange[]r,android.os.ParcelFileDescriptor f,android.os.CancellationSignal s,WriteResultCallback cb){try{for(int k=0;k<30;k++){int[][]g=new int[9][9];fill(g);int holes=34+(k%4)*7;for(int n=0;n<holes;n++)g[rnd.nextInt(9)][rnd.nextInt(9)]=0;android.graphics.pdf.PdfDocument.Page page=d.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,k).create());Canvas c=page.getCanvas();Paint p=new Paint(3);p.setTextAlign(Paint.Align.CENTER);p.setTypeface(Typeface.DEFAULT_BOLD);p.setColor(Color.rgb(35,40,70));p.setTextSize(28);c.drawText("🧩 סודוקו קסום",297,55,p);p.setTextSize(14);c.drawText("חידה "+(k+1)+"  •  "+new String[]{"קל","בינוני","קשה","מומחה"}[k%4],297,82,p);drawPdf(c,g,90,120,420);p.setTextSize(11);c.drawText("פתרון עצמי • בהצלחה!",297,780,p);d.finishPage(page);}d.writeTo(f);cb.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});}catch(Exception e){cb.onWriteFailed(e.toString());}finally{d.close();}}},null);}
 void drawPdf(Canvas c,int[][]g,float x,float y,float size){Paint p=new Paint(3);float q=size/9;p.setStyle(Paint.Style.FILL);p.setColor(Color.WHITE);c.drawRect(x,y,x+size,y+size,p);p.setStyle(Paint.Style.STROKE);for(int i=0;i<=9;i++){p.setColor(Color.DKGRAY);p.setStrokeWidth(i%3==0?3:1);c.drawLine(x,y+i*q,x+size,y+i*q,p);c.drawLine(x+i*q,y,x+i*q,y+size,p);}p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(q*.5f);p.setColor(Color.rgb(30,35,55));for(int r=0;r<9;r++)for(int c1=0;c1<9;c1++)if(g[r][c1]>0)c.drawText(""+g[r][c1],x+(c1+.5f)*q,y+(r+.68f)*q,p);}
}