plugins {
    id 'com.android.application'
}

android {
    namespace 'com.d0548448174ai.chipmunk'
    compileSdk 35

    defaultConfig {
        applicationId 'com.d0548448174ai.chipmunk'
        minSdk 23
        targetSdk 28
        versionCode 3
        versionName '3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'dev.ffmpegkit-maintained:ffmpeg-kit-audio:8.1.7'
}
